In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [2]:
df = pd.read_csv("insurance.csv")
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [3]:
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [4]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'expenses'], dtype='str')

In [5]:
df.shape

(1338, 7)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 94.5 KB

In [7]:
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [8]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [9]:
df.dropna()

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [10]:
le = LabelEncoder()
df["sex"] = le.fit_transform(df["sex"])
df["smoker"] = le.fit_transform(df["smoker"])
df["region"] = le.fit_transform(df["region"])

In [11]:
X = df.drop("smoker", axis=1)
y = df["smoker"]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)
X_train

      age  sex   bmi  children  region  expenses
560    46    0  20.0         2       1   9193.84
1285   47    0  24.3         0       0   8534.67
1142   52    0  24.9         0       2  27117.99
969    39    0  34.3         5       2   8596.83
486    54    0  21.5         3       1  12475.35
...   ...  ...   ...       ...     ...       ...
1095   18    0  31.4         4       0   4561.19
1130   39    0  23.9         5       2   8582.30
1294   58    1  25.2         0       0  11931.13
860    37    0  47.6         2       3  46113.51
1126   55    1  29.9         0       3  10214.64

[1070 rows x 6 columns]

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[ 0.47222651, -1.0246016 , -1.74857248,  0.73433626, -0.45611589,
        -0.34562068],
       [ 0.54331294, -1.0246016 , -1.03670397, -0.91119211, -1.35325561,
        -0.400488  ],
       [ 0.8987451 , -1.0246016 , -0.93737348, -0.91119211,  0.44102382,
         1.14633119],
       ...,
       [ 1.3252637 ,  0.97598911, -0.88770823, -0.91119211, -1.35325561,
        -0.11777697],
       [-0.16755139, -1.0246016 ,  2.82063006,  0.73433626,  1.33816354,
         2.72746066],
       [ 1.1120044 ,  0.97598911, -0.1096194 , -0.91119211,  1.33816354,
        -0.26065239]], shape=(1070, 6))

In [14]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

In [15]:
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)

In [16]:
nb = GaussianNB()
nb.fit(X_train, y_train)
nb_pred = nb.predict(X_test)

In [17]:
comparison = pd.DataFrame({
    "Algorithm": [
        "Logistic Regression",
        "KNN",
        "Naive Bayes"
    ],

    "Accuracy": [
        accuracy_score(y_test, lr_pred),
        accuracy_score(y_test, knn_pred),
        accuracy_score(y_test, nb_pred)
    ],

    "Precision": [
        precision_score(y_test, lr_pred),
        precision_score(y_test, knn_pred),
        precision_score(y_test, nb_pred)
    ],

    "Recall": [
        recall_score(y_test, lr_pred),
        recall_score(y_test, knn_pred),
        recall_score(y_test, nb_pred)
    ],

    "F1 Score": [
        f1_score(y_test, lr_pred),
        f1_score(y_test, knn_pred),
        f1_score(y_test, nb_pred)
    ]
})

comparison

             Algorithm  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.958955   0.890909  0.907407  0.899083
1                  KNN  0.955224   0.875000  0.907407  0.890909
2          Naive Bayes  0.925373   0.826923  0.796296  0.811321

In [18]:
best = comparison.loc[comparison["Accuracy"].idxmax()]
print("Best Algorithm :", best["Algorithm"])
print("Accuracy :", best["Accuracy"])

Best Algorithm : Logistic Regression
Accuracy : 0.9589552238805971